[[main]]
    identifier = "home"
    name = "首页"
    url = "/"
    weight = -100
    [main.params]
        icon = "home"

[[main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = -90
    [main.params]
        icon = "archives"

[[main]]
    identifier = "search"
    name = "搜索"
    url = "/search/"
    weight = -80
    [main.params]
        icon = "search"

[[main]]
    identifier = "about"
    name = "关于我"
    url = "/about/"
    weight = -70
    [main.params]
        icon = "user"
